// GENERATED by scripts/gen-zone-domain.mjs — DO NOT EDIT.
//
// The TypeScript view of the zone domain, produced by EVALUATING the compiled
// core: `Editor.zone_type_names()` and `Editor.ground_zone_types()`. The single
// authoring point is `zone_domain!` in crates/ds-core/src/zone.rs.
//
// Editing this file by hand recreates the second authoring path that let a
// ninth variant be ground in Rust and not-ground in TypeScript with every board
// green. `make wasm` regenerates it; `node scripts/gen-zone-domain.mjs --check`
// is a battery step, so staleness is a build failure.

import type { ZoneType } from './doc.ts'

/** Every `ZoneType`, in declaration order. */
export const ALL_ZONE_TYPES: readonly ZoneType[] = [
  'Circulation',
  'Workspace',
  'Meeting',
  'Collaboration',
  'Core',
  'ClosedOffice',
  'Amenity',
  'Unassigned',
]

/** The types the published fold turns into circulation, plus circulation. */
export const GENERATED_GROUND_ZONES: readonly ZoneType[] = [
  'Circulation',
  'Unassigned',
]
