// Sheets manager + publish (M6 — Rayon-parity). A thin controller over the
// drawing-set exporter: it lists the sheets of the architectural set, lets the
// user pick which to include and fill the title-block / project metadata, then
// PUBLISHES by calling exportDrawingSet(state, opts, filename) as-is.
//
// It owns NO document or PDF logic. The sheet *content* is generated by
// web/src/export/sheetSet.ts (buildDrawingSetPdf); the sheet *list* is the pure
// descriptor in web/src/export/sheetManifest.ts. This panel only assembles the
// DrawingSetOpts.meta from the form and hands it to the exporter.
//
// The include toggles are load-bearing: buildOpts() passes the checked sheet ids
// as DrawingSetOpts.include, and the exporter emits only those sheets (a
// de-selected sheet's builder never runs). Sheets marked available:false in the
// manifest are still being built by the engine and stay disabled here.

import { useEffect, useMemo, useState } from 'react'
import { exportDrawingSet, type DrawingSetOpts } from '../export/sheetSet'
import { SHEET_MANIFEST } from '../export/sheetManifest'
import type { EditorCanvas } from '../editor/EditorCanvas'
import type { Drawing } from '../import/types'
import type { BindingInfo } from '../persist/file'
import type { ProjectRecord } from '../persist/projects'

export interface SheetsPanelProps {
  ec: EditorCanvas | null
  /** Active project — seeds the title-block fields. */
  project: ProjectRecord | null
  /** Imported original (seeds the demolition plan) — passed straight through. */
  drawing: Drawing | null
  /** Product bindings — passed straight through to the exporter. */
  bindings: Map<string, BindingInfo>
  onClose: () => void
}

/** Editable title-block fields that actually feed DrawingSetOpts.meta. */
interface TitleBlock {
  project: string
  client: string
  address: string
  revision: string
  drawnBy: string
  approvedBy: string
  studio: string
}

/** Today's date in the same format sheetSet.ts stamps on every sheet. */
function todayLabel(): string {
  return new Date().toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' })
}

function slug(s: string): string {
  return s.trim().toLowerCase().replace(/[^\w]+/g, '-').replace(/^-+|-+$/g, '') || 'dsource'
}

export function SheetsPanel({ ec, project, drawing, bindings, onClose }: SheetsPanelProps) {
  // Title-block state — seeded once from the active project (workflow.md §2).
  const [tb, setTb] = useState<TitleBlock>(() => ({
    project: project?.name ?? 'Untitled Plan',
    client: project?.propertyName ?? '',
    address: project?.address ?? '',
    revision: 'A',
    drawnBy: '',
    approvedBy: '',
    studio: 'DSOURCE',
  }))

  // Include map — every available sheet starts included; "soon" sheets can't be.
  const [included, setIncluded] = useState<Record<string, boolean>>(() =>
    Object.fromEntries(SHEET_MANIFEST.map((s) => [s.id, s.available])),
  )

  const [busy, setBusy] = useState(false)
  const [notice, setNotice] = useState<string | null>(null)

  // Esc closes (the panel is a modal overlay; scrim click also closes).
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation()
        onClose()
      }
    }
    window.addEventListener('keydown', onKey, true)
    return () => window.removeEventListener('keydown', onKey, true)
  }, [onClose])

  const set = (k: keyof TitleBlock) => (e: React.ChangeEvent<HTMLInputElement>) =>
    setTb((prev) => ({ ...prev, [k]: e.target.value }))

  const availCount = SHEET_MANIFEST.filter((s) => s.available).length
  const inclCount = SHEET_MANIFEST.filter((s) => s.available && included[s.id]).length

  const canPublish = !!ec && inclCount > 0 && !busy

  // Assemble the exporter options from the form. blank → undefined so the
  // exporter's own field-presence checks (it hides empty lines) still work.
  // `include` = the checked, available sheet ids — the exporter emits only these
  // (see sheetSet.ts DrawingSetOpts.include); omitting a sheet skips its builder.
  const buildOpts = (): DrawingSetOpts => {
    const t = (v: string) => (v.trim() ? v.trim() : undefined)
    return {
      meta: {
        project: t(tb.project) ?? 'Untitled Plan',
        client: t(tb.client),
        address: t(tb.address),
        floor: project?.floor,
        logo: project?.logo,
        studio: t(tb.studio) ?? 'DSOURCE',
        revision: t(tb.revision),
        drawnBy: t(tb.drawnBy),
        approvedBy: t(tb.approvedBy),
      },
      drawing,
      bindings,
      include: SHEET_MANIFEST.filter((s) => s.available && included[s.id]).map((s) => s.id),
    }
  }

  const publish = async () => {
    if (!ec) return
    setBusy(true)
    setNotice(null)
    try {
      const opts = buildOpts()
      const filename = `${slug(tb.project)}-drawing-set.pdf`
      await exportDrawingSet(ec.getState(), opts, filename)
      setNotice(`Published ${inclCount} sheet${inclCount === 1 ? '' : 's'} → ${filename}`)
    } catch (err) {
      setNotice(`Publish failed: ${err instanceof Error ? err.message : String(err)}`)
    } finally {
      setBusy(false)
    }
  }

  const fields = useMemo(
    () =>
      [
        { key: 'project', label: 'Project', value: tb.project, ph: 'Project name' },
        { key: 'client', label: 'Client', value: tb.client, ph: 'Client / property' },
        { key: 'address', label: 'Address', value: tb.address, ph: 'Site address' },
        { key: 'revision', label: 'Revision', value: tb.revision, ph: 'A', num: true },
        { key: 'studio', label: 'Studio', value: tb.studio, ph: 'DSOURCE' },
        { key: 'drawnBy', label: 'Drawn by', value: tb.drawnBy, ph: 'Initials' },
        { key: 'approvedBy', label: 'Approved by', value: tb.approvedBy, ph: 'Initials' },
      ] as { key: keyof TitleBlock; label: string; value: string; ph: string; num?: boolean }[],
    [tb],
  )

  return (
    <div className="sheets-scrim" onMouseDown={onClose} data-testid="sheets-panel">
      <div
        className="sheets-panel"
        role="dialog"
        aria-modal="true"
        aria-label="Sheets manager"
        onMouseDown={(e) => e.stopPropagation()}
      >
        <header className="sheets-head">
          <div>
            <div className="sheets-eyebrow">Drawing set</div>
            <h2 className="sheets-title">Sheets &amp; publish</h2>
          </div>
          <button className="sheets-close" onClick={onClose} aria-label="Close sheets manager" title="Close (Esc)">
            <kbd>esc</kbd>
          </button>
        </header>

        <div className="sheets-cols">
          {/* Sheet list ------------------------------------------------------ */}
          <section className="sheets-list-col" aria-label="Sheets">
            <div className="sheets-colhead">
              <span>Sheets</span>
              <span className="num sheets-count">
                {inclCount} / {availCount}
              </span>
            </div>
            <div className="sheets-list">
              {SHEET_MANIFEST.map((s) => (
                <label
                  key={s.id}
                  className={`sheet-row${s.available ? '' : ' soon'}${included[s.id] && s.available ? ' on' : ''}`}
                  data-testid={`sheet-row-${s.id}`}
                >
                  <input
                    type="checkbox"
                    className="sheet-check"
                    data-testid={`sheet-include-${s.id}`}
                    checked={!!included[s.id] && s.available}
                    disabled={!s.available}
                    onChange={(e) => setIncluded((prev) => ({ ...prev, [s.id]: e.target.checked }))}
                    aria-label={`Include ${s.title}`}
                  />
                  <span className="sheet-no num">{s.no}</span>
                  <span className="sheet-main">
                    <span className="sheet-name">
                      {s.title}
                      {!s.available && <span className="sheet-soon">soon</span>}
                    </span>
                    <span className="sheet-blurb">{s.blurb}</span>
                  </span>
                </label>
              ))}
            </div>
            <p className="sheets-foot">
              Toggles select which sheets to publish. Greyed sheets are still being built by the
              engine and appear here as they come online.
            </p>
          </section>

          {/* Title block ----------------------------------------------------- */}
          <section className="sheets-meta-col" aria-label="Title block">
            <div className="sheets-colhead">
              <span>Title block</span>
            </div>
            <div className="tb-grid">
              {fields.map((f) => (
                <label key={f.key} className="tb-field">
                  <span className="tb-label">{f.label}</span>
                  <input
                    className={f.num ? 'tb-input num' : 'tb-input'}
                    data-testid={`titleblock-field-${f.key}`}
                    value={f.value}
                    placeholder={f.ph}
                    onChange={set(f.key)}
                    spellCheck={false}
                    autoComplete="off"
                  />
                </label>
              ))}
              {/* Auto-derived per-sheet fields — shown for a complete title block
                  but computed by the engine (date = today, scale = plot scale). */}
              <label className="tb-field">
                <span className="tb-label">Date</span>
                <input
                  className="tb-input num tb-auto"
                  data-testid="titleblock-field-date"
                  value={todayLabel()}
                  readOnly
                  aria-readonly
                  title="Stamped automatically on every sheet"
                />
              </label>
              <label className="tb-field">
                <span className="tb-label">Scale</span>
                <input
                  className="tb-input num tb-auto"
                  data-testid="titleblock-field-scale"
                  value="Auto · per sheet"
                  readOnly
                  aria-readonly
                  title="Each sheet prints its own 1:N plot scale"
                />
              </label>
            </div>
          </section>
        </div>

        <footer className="sheets-actions">
          {notice && (
            <span className="sheets-notice" role="status">
              {notice}
            </span>
          )}
          <span className="sheets-spring" />
          <button
            className="sheets-publish"
            data-testid="sheets-publish"
            onClick={() => void publish()}
            disabled={!canPublish}
            title={ec ? 'Build and download the branded drawing-set PDF' : 'Open a plan first'}
          >
            {busy ? 'Publishing…' : `Publish set (${inclCount})`}
          </button>
        </footer>
      </div>
    </div>
  )
}
