// Print export actions: DocState + Metrics -> a downloaded PDF, plus the A3
// sheet chrome the two actions compose on.
//
// Hand-written like our DXF R12 exporter (no jsPDF/pdf-lib): the plan is
// rasterised by ./printPlan and embedded as a JPEG image XObject
// (/Filter /DCTDecode); the title block, key metrics and furniture schedule are
// vector text in the built-in /Helvetica, so they stay crisp and selectable.
//
// The byte writer lives in ./pdfDoc and the palette-bearing raster in
// ./printPlan (R1). What is left here is sheet composition and the two actions.

import type { DocState, DocComponent } from '../types/doc'
import type { Metrics } from '../types/metrics'
import type { Drawing, DrawEntity } from '../import/types'
import { CATEGORY_COLOR } from '../import/types'
import { triggerDownload } from './png'
import { ZONE, PRINT, planStyle, hexToRgb01 } from '../editor/planStyle'
import { PAGE_W, PAGE_H, pdfSafeText, textWidth, buildPdfBytes } from './pdfDoc'
import type { PdfMeta, ContentOp } from './pdfDoc'
import { PRINT_ZONE_FILL, renderPrintCanvas, planScaleN, canvasToJpeg } from './printPlan'

// ---------------------------------------------------------------------------
// Sheet composition
// ---------------------------------------------------------------------------

const MARGIN = 24
const PANEL_W = 300
const PAD = 12

// Truncate with "..." to fit a width (Helvetica estimate).
function clipText(s: string, size: number, bold: boolean, maxW: number): string {
  if (textWidth(s, size, bold) <= maxW) return s
  let t = s
  while (t.length > 1 && textWidth(t + '...', size, bold) > maxW) t = t.slice(0, -1)
  return t + '...'
}

// "MeetingRoom" -> "MEETING ROOM" for schedule rows.
function categoryName(category: string): string {
  return category.replace(/([a-z0-9])([A-Z])/g, '$1 $2').toUpperCase()
}

function fmt(v: number | undefined, f: (n: number) => string): string {
  return v === undefined ? '-' : f(v)
}

const RES = 2.6 // px per pt: ~187 dpi on paper, crisp for line-work

/** Plan-image placement (left of the panel divider) + raster size, shared by both sheets. */
function planImageRect() {
  const dividerX = PAGE_W - MARGIN - PANEL_W
  const img = {
    x: MARGIN + PAD,
    yTop: MARGIN + PAD, // top-down; converted to PDF space at the image op
    w: dividerX - MARGIN - PAD * 2,
    h: PAGE_H - (MARGIN + PAD) * 2,
  }
  return { img, wPx: Math.round(img.w * RES), hPx: Math.round(img.h * RES) }
}

/** True plot scale "1 : N @ A3" — meters per point on paper vs. meters per mm real. */
function scaleNote(metersPerPx: number, wPx: number, imgW: number): string {
  const n = planScaleN(metersPerPx, wPx, imgW)
  return n === 0 ? 'N.T.S.' : `1 : ${n} @ A3`
}

/**
 * Shared A3 sheet chrome: outer frame, right-panel divider, top-down `text`/
 * `hr` helpers scoped to the panel, and the standard footer. Both sheet
 * exports (generated doc + imported drawing) compose their panels on this.
 */
function sheetChrome(ops: ContentOp[]) {
  const dividerX = PAGE_W - MARGIN - PANEL_W
  const Y = (yTop: number) => PAGE_H - yTop
  const px0 = dividerX + 18
  const px1 = PAGE_W - MARGIN - 18

  ops.push({
    op: 'rect',
    x: MARGIN,
    y: MARGIN,
    w: PAGE_W - MARGIN * 2,
    h: PAGE_H - MARGIN * 2,
    fill: false,
    gray: 0.25,
    width: 1.2,
  })
  ops.push({ op: 'line', x1: dividerX, y1: Y(MARGIN), x2: dividerX, y2: MARGIN, width: 1.2, gray: 0.25 })

  const text = (
    x: number,
    yTop: number,
    size: number,
    s: string,
    o?: { bold?: boolean; gray?: number; align?: 'left' | 'right' },
  ) => {
    const w = textWidth(pdfSafeText(s), size, o?.bold)
    ops.push({
      op: 'text',
      x: o?.align === 'right' ? x - w : x,
      y: Y(yTop),
      size,
      text: s,
      bold: o?.bold,
      gray: o?.gray,
    })
  }
  const hr = (yTop: number, gray = 0.75) =>
    ops.push({ op: 'line', x1: px0, y1: Y(yTop), x2: px1, y2: Y(yTop), width: 0.7, gray })

  const footTop = PAGE_H - MARGIN - 24 // footer band top (top-down y)
  const footer = () => {
    hr(footTop)
    text(px0, footTop + 14, 6.5, 'GENERATED BY DSOURCE EDITOR', { gray: 0.55 })
    text(
      px1,
      footTop + 14,
      6.5,
      new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: false }),
      { align: 'right', gray: 0.55 },
    )
  }

  return { Y, px0, px1, panelW: px1 - px0, text, hr, footTop, footer }
}

/**
 * Export the current plan as a print-ready A3 landscape PDF drawing sheet:
 * plan image on the left, title block + key metrics + furniture schedule in a
 * right-hand panel. Downloads via the shared blob plumbing.
 */
export async function exportPlanPDF(
  state: DocState,
  metrics: Metrics,
  meta?: PdfMeta,
  filename = 'dsource-plan.pdf',
): Promise<void> {
  // --- plan image ------------------------------------------------------
  const { img, wPx, hPx } = planImageRect()
  const { canvas, metersPerPx } = renderPrintCanvas(state, wPx, hPx)
  const jpegBytes = canvasToJpeg(canvas)

  // --- content ops (built top-down, converted to PDF space) -------------
  const ops: ContentOp[] = []
  ops.push({ op: 'image', x: img.x, y: PAGE_H - (img.yTop + img.h), w: img.w, h: img.h })
  const { Y, px0, px1, panelW, text, hr, footTop, footer } = sheetChrome(ops)

  // --- title block -------------------------------------------------------
  let y = MARGIN + 32
  text(px0, y, 8, 'DSOURCE EDITOR', { gray: 0.45 })
  y += 24
  text(px0, y, 16, clipText(pdfSafeText(meta?.project ?? 'Untitled Project'), 16, true, panelW), {
    bold: true,
    gray: 0.05,
  })
  y += 20
  text(px0, y, 11, meta?.title ?? 'FURNITURE PLAN', { gray: 0.3 })
  y += 14
  hr(y)

  const metaRow = (label: string, value: string) => {
    y += 17
    text(px0, y, 7.5, label, { gray: 0.5 })
    text(px1, y, 9, value, { align: 'right', gray: 0.1 })
  }
  metaRow(
    'DATE',
    new Date()
      .toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
      .toUpperCase(),
  )
  metaRow('SCALE', scaleNote(metersPerPx, wPx, img.w))
  metaRow('SHEET', 'A-101')
  y += 12
  hr(y)

  // --- key metrics ---------------------------------------------------------
  const gea = metrics.gross_external_area ?? metrics.floor_area
  const nia = metrics.net_internal_area
  const workstations =
    metrics.workstations ?? state.components.filter((c) => c.category === 'Desk').length
  const areaPerWs =
    metrics.area_per_workstation ??
    (nia !== undefined && workstations > 0 ? nia / workstations : undefined)
  const efficiency =
    metrics.efficiency_pct ?? (nia !== undefined && gea > 0 ? (nia / gea) * 100 : undefined)
  const inr = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 })

  y += 20
  text(px0, y, 9, 'KEY METRICS', { bold: true, gray: 0.3 })
  const metricRow = (label: string, value: string) => {
    y += 16.5
    text(px0, y, 8.5, label, { gray: 0.45 })
    text(px1, y, 9.5, value, { bold: true, align: 'right', gray: 0.08 })
  }
  const area = (n: number) => `${n.toFixed(1)} m²`
  metricRow('GROSS EXTERNAL AREA', fmt(gea, area))
  metricRow('NET INTERNAL AREA', fmt(nia, area))
  metricRow('WORKSTATIONS', `${workstations}`)
  metricRow('AREA / WORKSTATION', fmt(areaPerWs, area))
  metricRow('EFFICIENCY', fmt(efficiency, (n) => `${n.toFixed(0)}%`))
  // ₹ is not in WinAnsi/Helvetica, so cost prints as "Rs." with en-IN grouping.
  metricRow('FIT-OUT COST (INDICATIVE)', fmt(metrics.indicative_cost, (n) => `Rs. ${inr.format(n)}`))
  y += 12
  hr(y)

  // --- zone key -----------------------------------------------------------
  // ON PAPER THE LEGEND IS THE ONLY IDENTIFICATION THERE IS. The paper profile
  // prints service-room abbreviations and nothing else (that is what the
  // reference does), so without this the sheet is not reference-minimal, it is
  // unreadable. The on-canvas legend lives in the right-hand UI panel, which is
  // not part of the exported sheet -- so it has to be drawn here too.
  //
  // DERIVED from the state's own zones, exactly like the canvas legend: a plan
  // with no breakout prints no breakout swatch. Colours come from ZONE via
  // PRINT_ZONE_FILL, so the sheet and the canvas cannot disagree about what a
  // colour means.
  const paperStyle = planStyle('paper')
  const zoneKinds: string[] = []
  for (const z of state.zones ?? []) {
    if (paperStyle.groundZones.includes(z.zone_type)) continue // ground has no swatch
    if (!zoneKinds.includes(z.zone_type)) zoneKinds.push(z.zone_type)
  }
  if (zoneKinds.length > 0) {
    y += 20
    text(px0, y, 9, 'ZONE KEY', { bold: true, gray: 0.3 })
    for (const kind of zoneKinds) {
      y += 15
      const rgb = hexToRgb01(PRINT_ZONE_FILL[kind] ?? PRINT_ZONE_FILL.Core)
      ops.push({ op: 'rect', x: px0, y: Y(y + 1.5), w: 9, h: 9, fill: true, rgb })
      ops.push({ op: 'rect', x: px0, y: Y(y + 1.5), w: 9, h: 9, fill: false, gray: 0.6, width: 0.5 })
      text(px0 + 15, y, 8.5, kind.replace(/([a-z])([A-Z])/g, '$1 $2').toUpperCase(), { gray: 0.3 })
    }
    y += 12
    hr(y)
  }

  // --- furniture schedule --------------------------------------------------
  const counts = new Map<string, number>()
  for (const c of state.components as DocComponent[]) {
    counts.set(c.category, (counts.get(c.category) ?? 0) + 1)
  }
  const schedule = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))

  y += 20
  text(px0, y, 9, 'FURNITURE SCHEDULE', { bold: true, gray: 0.3 })
  y += 10
  ops.push({ op: 'rect', x: px0, y: Y(y + 13), w: panelW, h: 14, fill: true, gray: 0.93 })
  y += 10.5
  text(px0 + 5, y, 7.5, 'ITEM', { bold: true, gray: 0.35 })
  text(px1 - 5, y, 7.5, 'QTY', { bold: true, align: 'right', gray: 0.35 })
  y += 2.5

  const rowH = 14.5
  const maxRows = Math.max(0, Math.floor((footTop - 12 - (y + rowH * 2)) / rowH))
  const shown = schedule.length > maxRows ? schedule.slice(0, Math.max(0, maxRows - 1)) : schedule
  for (const [category, count] of shown) {
    y += rowH
    text(px0 + 5, y, 9, clipText(categoryName(category), 9, false, panelW - 60), { gray: 0.2 })
    text(px1 - 5, y, 9, `${count}`, { align: 'right', gray: 0.1 })
    hr(y + 4, 0.88)
  }
  if (shown.length < schedule.length) {
    const rest = schedule.slice(shown.length)
    y += rowH
    text(px0 + 5, y, 9, `+ ${rest.length} MORE CATEGORIES`, { gray: 0.5 })
    text(px1 - 5, y, 9, `${rest.reduce((s, [, n]) => s + n, 0)}`, { align: 'right', gray: 0.35 })
    hr(y + 4, 0.88)
  }
  y += rowH
  text(px0 + 5, y, 9, 'TOTAL', { bold: true, gray: 0.15 })
  text(px1 - 5, y, 9.5, `${state.components.length}`, { bold: true, align: 'right', gray: 0.05 })

  footer()

  const pdf = buildPdfBytes(ops, { bytes: jpegBytes, width: wPx, height: hPx })
  triggerDownload(new Blob([pdf], { type: 'application/pdf' }), filename)
}

// ---------------------------------------------------------------------------
// Imported-plan sheet (CAD Drawing -> same A3 sheet)
// ---------------------------------------------------------------------------

// Fork of DrawingCanvas's on-screen pipeline, not a reuse: the live canvas is
// an interactive class (DPR viewport, pan/zoom state, hover/selection chrome,
// bound-item accenting) — print needs a one-shot clean raster on white.

/**
 * Render an imported drawing to an offscreen canvas: architecture linework
 * (walls/glazing/doors/…) stroked by category color, furniture as light bbox
 * outlines. CAD world is Y-up, so Y is flipped. Returns `metersPerPx` for the
 * plot-scale note (0 = degenerate bounds).
 */
function renderDrawingPrintCanvas(
  drawing: Drawing,
  wPx: number,
  hPx: number,
): { canvas: HTMLCanvasElement; metersPerPx: number } {
  const canvas = document.createElement('canvas')
  canvas.width = wPx
  canvas.height = hPx
  const ctx = canvas.getContext('2d')
  if (!ctx) return { canvas, metersPerPx: 0 }

  ctx.fillStyle = PRINT.paper
  ctx.fillRect(0, 0, wPx, hPx) // JPEG has no alpha — must paint the background.

  const [minX, minY, maxX, maxY] = drawing.bounds
  const pad = 48
  const spanX = Math.max(maxX - minX, 0.001)
  const spanY = Math.max(maxY - minY, 0.001)
  const k = Math.min((wPx - pad * 2) / spanX, (hPx - pad * 2) / spanY)
  const X = (m: number) => m * k + (wPx - spanX * k) / 2 - minX * k
  const Yc = (m: number) => -m * k + (hPx + spanY * k) / 2 + minY * k // Y-up -> Y-down

  // Same subpath math as DrawingCanvas.appendEntity (angles negate on Y flip).
  const path = (e: DrawEntity) => {
    if (e.kind === 'polyline') {
      const pts = e.pts
      if (!pts || pts.length === 0) return
      ctx.moveTo(X(pts[0][0]), Yc(pts[0][1]))
      for (let i = 1; i < pts.length; i++) ctx.lineTo(X(pts[i][0]), Yc(pts[i][1]))
      if (e.closed) ctx.lineTo(X(pts[0][0]), Yc(pts[0][1]))
    } else if (e.kind === 'circle' || e.kind === 'arc') {
      if (e.cx === undefined || e.cy === undefined || e.r === undefined) return
      const rPx = e.r * k
      const a0 = e.kind === 'circle' ? 0 : -(e.start ?? 0)
      const a1 = e.kind === 'circle' ? Math.PI * 2 : -(e.end ?? Math.PI * 2)
      ctx.moveTo(X(e.cx) + rPx * Math.cos(a0), Yc(e.cy) + rPx * Math.sin(a0))
      ctx.arc(X(e.cx), Yc(e.cy), rPx, a0, a1, e.kind === 'arc')
    }
  }

  ctx.lineCap = 'round'
  ctx.lineJoin = 'round'
  for (const e of drawing.entities) {
    if (e.kind === 'text') continue // sheet text stays vector in the panel
    ctx.strokeStyle = e.color ?? CATEGORY_COLOR[e.category] ?? CATEGORY_COLOR.other
    ctx.lineWidth =
      e.category === 'wall' ? 2 : e.category === 'annotation' || e.category === 'dimension' ? 0.6 : 1
    ctx.beginPath()
    path(e)
    ctx.stroke()
  }

  // Furniture as light outlines — occupancy reads on paper without the
  // (heavy) flattened block linework.
  ctx.strokeStyle = PRINT.rule
  ctx.lineWidth = 1
  for (const f of drawing.furniture) {
    const [x0, y0, x1, y1] = f.bbox
    ctx.strokeRect(X(x0), Yc(y1), (x1 - x0) * k, (y1 - y0) * k)
  }

  return { canvas, metersPerPx: k > 0 ? 1 / k : 0 }
}

/**
 * Export an IMPORTED plan as a print-ready A3 landscape PDF sheet: the drawing
 * raster on the left, title block + import metrics (extent, furniture count,
 * specified count + ₹ total) in the right-hand panel. Shares the byte writer
 * and sheet chrome with `exportPlanPDF`.
 */
export async function exportDrawingPDF(
  drawing: Drawing,
  opts: { boundCount: number; specTotalInr: number | null },
  filename = 'dsource-import.pdf',
): Promise<void> {
  const { img, wPx, hPx } = planImageRect()
  const { canvas, metersPerPx } = renderDrawingPrintCanvas(drawing, wPx, hPx)
  const jpegBytes = canvasToJpeg(canvas)

  const ops: ContentOp[] = []
  ops.push({ op: 'image', x: img.x, y: PAGE_H - (img.yTop + img.h), w: img.w, h: img.h })
  const { px0, px1, panelW, text, hr, footer } = sheetChrome(ops)

  // --- title block -------------------------------------------------------
  let y = MARGIN + 32
  text(px0, y, 8, 'DSOURCE EDITOR', { gray: 0.45 })
  y += 24
  text(px0, y, 16, clipText('Untitled Project', 16, true, panelW), { bold: true, gray: 0.05 })
  y += 20
  text(px0, y, 11, 'IMPORTED PLAN', { gray: 0.3 })
  y += 14
  hr(y)

  const metaRow = (label: string, value: string) => {
    y += 17
    text(px0, y, 7.5, label, { gray: 0.5 })
    text(px1, y, 9, value, { align: 'right', gray: 0.1 })
  }
  metaRow(
    'DATE',
    new Date()
      .toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
      .toUpperCase(),
  )
  metaRow('SCALE', scaleNote(metersPerPx, wPx, img.w))
  metaRow('SHEET', 'A-201')
  y += 12
  hr(y)

  // --- import metrics ------------------------------------------------------
  const extentW = drawing.bounds[2] - drawing.bounds[0]
  const extentH = drawing.bounds[3] - drawing.bounds[1]
  const inr = new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 })

  y += 20
  text(px0, y, 9, 'IMPORT METRICS', { bold: true, gray: 0.3 })
  const metricRow = (label: string, value: string) => {
    y += 16.5
    text(px0, y, 8.5, label, { gray: 0.45 })
    text(px1, y, 9.5, value, { bold: true, align: 'right', gray: 0.08 })
  }
  metricRow('EXTENT', `${extentW.toFixed(1)} × ${extentH.toFixed(1)} m`)
  metricRow('FURNITURE ITEMS', `${drawing.furniture.length}`)
  metricRow('LINE ENTITIES', `${drawing.entities.length}`)
  metricRow('LAYERS', `${drawing.layers.length}`)
  metricRow('SPECIFIED', `${opts.boundCount} OF ${drawing.furniture.length}`)
  // ₹ is not in WinAnsi/Helvetica, so the total prints as "Rs." (pdfSafeText).
  metricRow(
    'SPECIFIED TOTAL',
    opts.specTotalInr != null ? `Rs. ${inr.format(opts.specTotalInr)}` : '-',
  )
  y += 12
  hr(y)

  footer()

  const pdf = buildPdfBytes(ops, { bytes: jpegBytes, width: wPx, height: hPx })
  triggerDownload(new Blob([pdf], { type: 'application/pdf' }), filename)
}
